# Generated by Django 2.2 on 2019-12-18 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_app', '0002_commentmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='photomodel',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
