# Generated by Django 2.2 on 2019-12-19 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photo_app', '0003_photomodel_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photomodel',
            name='comment',
        ),
        migrations.AlterField(
            model_name='commentmodel',
            name='commented_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.UserModel'),
        ),
        migrations.AlterField(
            model_name='commentmodel',
            name='parent_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photo_app.PhotoModel'),
        ),
    ]
