# Generated by Django 2.2 on 2019-12-22 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo_app', '0005_auto_20191222_0943'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photomodel',
            old_name='uploaded_by',
            new_name='user',
        ),
    ]
