# Generated by Django 2.2 on 2019-12-22 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo_app', '0006_auto_20191222_0946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photomodel',
            old_name='user',
            new_name='uploaded_by',
        ),
    ]
